Feature/add relationship between stores and products tables
FAP2024-Turma02/warranty-manager pull request #11
Opened 2024-09-27 14:55 UTC by Carlosguimara

1- Criar o relacionamento entre tabelas Stores(1) para products(N) a nivel de model

2- Compatibilizar Model Store com definição a nivel de BD

2024-09-30 17:09 UTC, pablomorato1 requested changes

2024-09-30 17:09 UTC, pablomorato1 commented on db/migrate/20240927135617_add_foreign_key_to_products.rb
> +    add_foreign_key :products, :stores
💣 
O metodo que deve ser usado aqui se chama: `add_reference`

2024-09-30 17:09 UTC, pablomorato1 commented on db/schema.rb
> +    t.bigint "product_id", null: false
Isso aqui deve ter ficado de resquicio de alguma outra migração
Tanto que a tabela que está sendo alterada é a de `warranties`

2024-10-01 01:08 UTC, Rochafelip commented on db/migrate/20240927135617_add_foreign_key_to_products.rb
> +    add_foreign_key :products, :stores
Corrigido PR#11, adicionando o metodo _add_reference_

2024-10-01 12:52 UTC, merged