PR para mandar a branch Feature/configurar_devise_token_auth para main.
FAP2024-Turma02/warranty-manager pull request #14
Opened 2024-09-28 14:57 UTC by Rochafelip

**Alterações:**

* **Gemfile:**
  * Adicionado o gem `devise_token_auth`.
* **Model User:**
  * Adicionados os campos necessários para o Devise Token Auth (tokens, confirmação por email, etc.).
  * Configuradas as associações e validações.
* **Routes:**
  * Criadas as rotas para registro, login, recuperação de senha e outras ações relacionadas à autenticação via token.
* **Controllers:**
  * Implementados os controllers para as ações de autenticação, seguindo as convenções do Devise Token Auth.

2024-09-30 17:01 UTC, pablomorato1 commented on db/migrate/20240906124512_devise_create_users.rb
> +    add_index :users, :unlock_token,         unique: true
💣 💣 💣 

Não se mexe em migrações antigas que já foram rodadas
Discutimos isso em sala na semana passada.

2024-09-30 19:57 UTC, Rochafelip commented on config/routes.rb
> +  resources :users, only: [:index, :show, :update, :destroy]
Enviei um commit com a substituição do '''only: [:index, :show, :update, :destroy]''' para ''' except: :create'''

2024-09-30 19:57 UTC, Rochafelip commented on app/controllers/users_controller.rb
> +    before_action :authenticate_user!, only: [:index, :show, :update, :destroy]
Enviei um commit com a substituição do '''only: [:index, :show, :update, :destroy]''' para ''' except: :create'''

2024-10-02 22:58 UTC, pablomorato1 requested changes

2024-10-02 22:58 UTC, pablomorato1 commented on db/schema.rb
> +    t.integer "failed_attempts", default: 0, null: false
No seu banco local ainda existe resquicio de alguma coluna não relacionada com as migrações deste PR

2024-10-07 19:40 UTC, pablomorato1 requested changes

2024-10-07 19:40 UTC, pablomorato1 commented on app/controllers/application_controller.rb
> +
Esses espaços no inicio e fim da classe não são necessarios

2024-10-07 19:40 UTC, pablomorato1 commented on app/controllers/application_controller.rb
>    include DeviseTokenAuth::Concerns::SetUserByToken
Remover linhas duplicada

2024-10-07 19:40 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
O que acontece na requisição se o ID não for encontrado?

2024-10-07 19:40 UTC, pablomorato1 commented on app/models/user.rb
> +       extend Devise::Models
Acredito que esta linha não seja necessaria.

2024-10-07 19:40 UTC, pablomorato1 commented on db/schema.rb
> -  add_foreign_key "warranties", "products"
Isso daqui era pra estar sendo removido?
Favor verificar as migrações e schema da main, caso exista migração e a linha na main será necessário ajustar seu banco de dados local.

2024-10-08 13:24 UTC, pablomorato1 requested changes

2024-10-17 14:27 UTC, closed without merging