Feature/model store
FAP2024-Turma02/warranty-manager pull request #22
Opened 2024-10-08 20:57 UTC by FabioBezerradeAndrade

# Adiciona Rota e Controller para a Model Store

## Descrição
Adiciona as rotas e o controller para a model `Store`, incluindo as ações `index` e `show`. As seguintes alterações foram feitas:

- Modificação no arquivo `routes.rb` para incluir as rotas `index` e `show` para `Store`.
- Criação do arquivo `stores_controller.rb` para gerenciar as requisições relacionadas à model `Store`.

2024-10-09 14:26 UTC, pablomorato1 requested changes

2024-10-09 14:26 UTC, pablomorato1 commented on app/controllers/stores_controller.rb
> +end
EOF

2024-10-09 15:14 UTC, FabioBezerradeAndrade commented on app/controllers/stores_controller.rb
> +end
Realizado a auteração.

Acrescentado a linha no final do código.

2024-10-15 13:40 UTC, pablomorato1 submitted a review, later dismissed
🥳

2024-10-17 19:12 UTC, pablomorato1 approved these changes

2024-10-17 19:17 UTC, merged