Adiciona pdf a requisição invoice
FAP2024-Turma02/warranty-manager pull request #23
Opened 2024-10-09 11:44 UTC by FabioBezerradeAndrade

# Adição da URL do PDF na Requisição da Model Invoice

## Descrição
Implementa a funcionalidade para incluir a URL do arquivo PDF associado a cada invoice na requisição da model `Invoice`. A implementação foi realizada utilizando a gem Active Storage (já presente na main) para gerenciar o upload e a associação dos arquivos PDF.

## Alterações Realizadas
- Atualização do `InvoicesController` para incluir a URL do PDF nas respostas das requisições `index` e `show`.

## Como Testar
Faça uma requisição GET para `/invoices` ou `/invoices/:id` e verifique se a resposta contém a URL do PDF associado.

2024-10-09 14:28 UTC, pablomorato1 requested changes

2024-10-09 14:28 UTC, pablomorato1 commented on app/controllers/invoices_controller.rb
> +  def invoice_response(invoice)
Isso tem que seguir o padrão que falamos em sala sobre ter um arquivo de `InvoiceSerializer`

2024-10-09 17:24 UTC, FabioBezerradeAndrade commented on app/controllers/invoices_controller.rb
> +  def invoice_response(invoice)
# Modificação do Controller de Invoice para Uso de Serializer

## Descrição das Alterações

1. **Modificação no Controller de Invoice**:
   - Foi atualizado para utilizar o método de serializer  no retorno dos dados das (`Invoice`).
   - A função `invoice_response` foi removida, sendo substituída pelo `InvoiceSerializer`, que agora lida com a serialização dos dados das invoices.

2. **Criação da pasta `serializers`**:
   - Uma nova pasta `app/serializers/` foi criada para armazenar os serializers.

3. **Criação do arquivo `invoice_serializer.rb`**:
   - Foi adicionado o arquivo `invoice_serializer.rb`, que define o serializer para a model `Invoice`, incluindo os atributos:
     - `id`
     - `invoice_number`
     - `purchase_date`
     - `issue_date`
     - `user_id`
     - `pdf_url`: gerido pelo Active Storage.

No aguardo mestre.

2024-10-15 13:47 UTC, pablomorato1 requested changes

2024-10-15 13:47 UTC, pablomorato1 commented on app/controllers/invoices_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
Se a tratativa da exception vai ser feita por meio de um metodo dedicado, ela deve estar no application controller e deve possuir uma logica abstraída para que todos os controllers possam utilizar o mesmo metodo.

2024-10-15 13:47 UTC, pablomorato1 commented on app/controllers/invoices_controller.rb
> +    render json: InvoiceSerializer.new(@invoice).serialize
O serializer deve ser uma classe com o conceito de `callable`
Pelo principio de Single Responsibility, a qualquer classe `NomeDoModelSerializer` só vai ter a função de serializar algo, então fica redundante ter que inicializar a classe e chamar um metodo `serialize` pra uma classe que só vai fazer isso.
O ideal é ajustar o serializer para que a chamada fique parecida com `InvoiceSerializer.call(invoice)`

2024-10-15 13:47 UTC, pablomorato1 commented on app/controllers/invoices_controller.rb
> +    render json: { error: 'Invoice not found' }, status: :not_found
No tratamento da exception que chama esse método, vc pode usar o I18N para padronizar o texto gerado quando o método for chamado independente do model que esteja dando erro.

2024-10-15 13:47 UTC, pablomorato1 commented on app/serializers/invoice_serializer.rb
> +
EOF

2024-10-23 22:16 UTC, pablomorato1 approved these changes

2024-10-24 12:29 UTC, merged