Adiciona autenticação com Devise Token Auth e rota.
FAP2024-Turma02/warranty-manager pull request #24
Opened 2024-10-09 12:40 UTC by Rochafelip

### O que foi feito
- Implementação da autenticação de usuários utilizando a gem Devise Token Auth.
- Criação de rotas customizadas para `/auth/test` que verificam a autenticação do usuário.
- Ajustes no model `User` para incluir os módulos Devise necessários (confirmable, lockable , etc.).

2024-10-09 14:31 UTC, pablomorato1 requested changes

2024-10-09 14:31 UTC, pablomorato1 commented on app/models/user.rb
> +                include DeviseTokenAuth::Concerns::User
indentação

2024-10-09 14:31 UTC, pablomorato1 commented on db/migrate/20241009120927_devise_token_auth_create_users.rb
> +class DeviseTokenAuthCreateUsers < ActiveRecord::Migration[7.0]
Esta migração foi rodada corretamente?
Se sim, no schema onde estão as colunas novas que ela adiciona.

2024-10-09 15:20 UTC, Rochafelip commented on app/models/user.rb
> +                include DeviseTokenAuth::Concerns::User
Foi ajustado

2024-10-09 15:34 UTC, Rochafelip commented on db/migrate/20241009120927_devise_token_auth_create_users.rb
> +class DeviseTokenAuthCreateUsers < ActiveRecord::Migration[7.0]
Acabei de dar db:drop db:create e db:migrate e enviei com novas alterações no schema

2024-10-15 13:50 UTC, pablomorato1 commented on app/models/invoice.rb
> +
Espaço a mais

2024-10-18 16:08 UTC, pablomorato1 submitted a review, later dismissed

2024-10-22 02:14 UTC, pablomorato1 submitted a review, later dismissed
🥳

2024-10-22 14:04 UTC, pablomorato1 submitted a review, later dismissed

2024-10-22 14:05 UTC, pablomorato1 submitted a review, later dismissed

2024-10-22 14:07 UTC, RenanAmendola submitted a review, later dismissed

2024-10-22 14:09 UTC, pablomorato1 approved these changes

2024-10-22 14:10 UTC, RenanAmendola approved these changes

2024-10-22 14:27 UTC, RenanAmendola approved these changes

2024-10-22 14:28 UTC, RenanAmendola submitted a review, later dismissed

2024-10-22 14:38 UTC, pablomorato1 approved these changes

2024-10-22 14:39 UTC, RenanAmendola approved these changes

2024-10-22 14:39 UTC, pablomorato1 submitted a review, later dismissed
Aprovado

2024-10-22 14:39 UTC, RenanAmendola submitted a review, later dismissed
aprovado

2024-10-22 17:10 UTC, closed without merging