Adicionar o Controller User na Main com index, show e create
FAP2024-Turma02/warranty-manager pull request #31
Opened 2024-10-25 14:58 UTC by Rochafelip

Adicionando o metodo index, show e create e corrigindo o modulo de devise para obter requisão /sign_in

2024-10-28 21:56 UTC, pablomorato1 requested changes

2024-10-28 21:56 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    render json: @user
Isso foi testado?
Não entendi, já estava certo antes chamando o metodo.

2024-10-28 21:56 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +      render json: { status: 'error', message: 'Falha ao criar usuário', errors: @user.errors.full_messages }, status: :unprocessable_entity
Isso ser um tratamento pra erro de ActiveRecord localizado no application controller.

2024-10-28 21:56 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    if @user.save
@user = User.create(user_params)

render json: { status: 'success', message: 'Usuário criado com sucesso', data: @user }, status: :created

Caso haja alguma exception ela deve ser tratada no ApplicationController.
Não é necessário fazer uma condiiconal pra isso.

2024-10-28 21:56 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
Você já tem o método `user` definido, não entendi porquê repetir a logica dele aqui.

2024-10-28 21:56 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +      redirect_to @user
Novamente, isso aqui foi testado?

2024-10-28 21:56 UTC, pablomorato1 commented on app/models/user.rb
> +        :rememberable, :validatable, :confirmable, :lockable
O que ocorreu pra ser necessario remover isso?

2024-10-28 22:29 UTC, Rochafelip commented on app/models/user.rb
> +        :rememberable, :validatable, :confirmable, :lockable
Como estava pedindo para se comunicar com current_sign_in_at do usuario e não foi implementado no modelo User, removir o modulo para continuar com os testes

2024-10-31 12:22 UTC, pablomorato1 requested changes

2024-10-31 12:22 UTC, pablomorato1 commented on app/controllers/application_controller.rb
> +      render json: { error: I18n.t('errors.email_already_exists') }, status: :unprocessable_entity
💣

2024-10-31 12:22 UTC, pablomorato1 commented on app/controllers/application_controller.rb
> +  rescue_from ActiveRecord::RecordInvalid, with: :email_already_exists
💣

2024-10-31 12:22 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    render json: UserSerializer.call(@user)
`UserSerializer.call(user)`

2024-10-31 12:22 UTC, pablomorato1 commented on app/serializers/user_serializer.rb
> +  attributes :id, :name, :email, :role, :admin, :created_at, :updated_at, :provider, :allow_password_change
💣

2024-11-04 18:52 UTC, pablomorato1 submitted a review, later dismissed
🥳

2024-11-05 13:43 UTC, pablomorato1 approved these changes

2024-11-05 13:45 UTC, RenanAmendola approved these changes

2024-11-05 13:46 UTC, merged